---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  alumni:
    title: alumni
    output: true
    permalink: "/:title/"
  visitors:
    title: visitors
    output: true
    permalink: "/:title/"
defaults:
- scope:
    path: ''
    type: alumni
  values:
    layout: default
- scope:
    path: ''
    type: visitors
  values:
    layout: default
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
permalink: pretty
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- npm-debug.log
- gulpfile.js
- sass
