---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  alumni:
    title: alumni
    output: true
    permalink: "/:title/"
  logos:
    title: logos
    output: true
    permalink: "/:title/"
  positions:
    title: positions
    output: true
    permalink: "/:title/"
defaults:
- scope:
    path: ''
    type: alumni
  values:
    layout: default
- scope:
    path: ''
    type: logos
  values:
    layout: default
- scope:
    path: ''
    type: positions
  values:
    layout: default
markdown: kramdown
theme: minima
permalink: pretty
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- npm-debug.log
- gulpfile.js
